"""
answer.py
---------
Turn raw query results into output a non-technical person can read:
  - to_text_table(): a clean aligned table (for transparency / "show the data").
  - summarize():     a short plain-English answer generated by the LLM,
                     grounded ONLY in the returned rows.
"""

SUMMARY_MODEL = "gpt-4o"


def to_text_table(columns, rows, max_rows=20):
    """Render rows as a simple aligned text table."""
    if not rows:
        return "(no rows)"

    cols = [str(c) for c in columns]
    widths = [len(c) for c in cols]
    shown = rows[:max_rows]

    str_rows = []
    for r in shown:
        cells = ["NULL" if v is None else str(v) for v in r]
        str_rows.append(cells)
        for i, cell in enumerate(cells):
            widths[i] = max(widths[i], len(cell))

    widths = [min(w, 40) for w in widths]  # cap very wide columns

    def fmt(cells):
        return " | ".join(c[:40].ljust(w) for c, w in zip(cells, widths))

    lines = [fmt(cols), "-+-".join("-" * w for w in widths)]
    lines += [fmt(cells) for cells in str_rows]
    if len(rows) > max_rows:
        lines.append(f"... ({len(rows)} rows returned)")
    return "\n".join(lines)


def _rows_to_text(columns, rows, max_rows=30):
    lines = [" | ".join(str(c) for c in columns)]
    for r in rows[:max_rows]:
        lines.append(" | ".join("" if v is None else str(v) for v in r))
    return "\n".join(lines), len(rows) > max_rows


SUMMARY_SYSTEM = (
    "You are a clinical-trials data assistant. Using ONLY the query results provided, "
    "answer the user's question in clear, plain English for a non-technical reader. "
    "Be concise (1-3 sentences) and state the key number(s) or finding(s). "
    "If the results are a list of records, describe them as the matching trials returned; "
    "do NOT claim it is a complete total unless the result is a single count. "
    "Never invent data beyond the results."
)


def summarize(openai_client, question, columns, rows):
    """Generate a brief plain-English answer grounded in the rows."""
    if not rows:
        return "No matching trials were found for that question."

    table_text, truncated = _rows_to_text(columns, rows)
    note = "\n(Only a sample of rows is shown.)" if truncated else ""
    user = (
        f"Question: {question}\n\n"
        f"Query results:\n{table_text}{note}\n\n"
        "Write a brief, plain-English answer."
    )
    resp = openai_client.chat.completions.create(
        model=SUMMARY_MODEL,
        messages=[
            {"role": "system", "content": SUMMARY_SYSTEM},
            {"role": "user", "content": user},
        ],
        temperature=0.2,
        max_tokens=200,
    )
    return resp.choices[0].message.content.strip()